M48
; DRILL file {KiCad (6.0.7)} date Tue Sep 20 09:24:32 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-20T09:24:32-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.0533Y-2.2642
X4.0533Y-2.4551
T2
X3.9341Y-2.2524
X3.9341Y-2.4669
T0
M30
